version: 2.1

executors:
  vms:
    machine: true
  dep:
    docker:
      - image: minepicco/cc-build-image:latest

workflows:

  build-deploy:
    jobs:
      - build_scan
      - hold:
          type: approval
          requires:
            - build_scan
          branches:
              only: master
      - deploy:
          requires:
            - hold
          branches:
              only: master

jobs:
  build_scan:
    executor: vms
    
    environment:
      dev_repo: "docker-local"
      prod_repo: "docker-prod"
      imagename: "artifactory.nohara/docker-local"
      
    steps:
      - checkout
      
      - run:
          name: Prepare Environment -- Install JFrog CLI
          command: |
            sudo apt-get update && sudo apt-get install -y python wget curl jq
            curl -fL https://getcli.jfrog.io | sh

      - run:
          name: Prepare Environment -- Add insecure-registries and hostname
          command: |
            echo '{ "insecure-registries" : ["artifactory.nohara"] }' > daemon.json
            sudo mv daemon.json /etc/docker/
            sudo cat /etc/hosts > hosts && echo $addr" artifactory.nohara" >> hosts
            sudo mv hosts /etc/
            sudo service docker restart
                     
      - run:
          name: Build Image
          command: |
            echo $CIRCLE_PROJECT_REPONAME
            docker build --tag $imagename"/"$CIRCLE_PROJECT_REPONAME":"$CIRCLE_BUILD_NUM .

      - run:
          name: JFrogCLI config
          command: |
            ./jfrog rt config --user=$juser --password=$jpass --url="http://artifactory.nohara/artifactory" $jid
      - run:
          name: JFrogCLI image push and scan
          command: |
            ./jfrog rt docker-push $imagename"/"$CIRCLE_PROJECT_REPONAME":"$CIRCLE_BUILD_NUM $dev_repo --build-name=$CIRCLE_PROJECT_REPONAME --build-number=$CIRCLE_BUILD_NUM
            ./jfrog rt bce $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM
            ./jfrog rt bag $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM
            ./jfrog rt bp $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM
            ./jfrog rt bs $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM
      - run:
          name: JFrogCLI promote image to production
          command: |
            ./jfrog rt bpr $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM $prod_repo

  deploy:
    executor: dep
    environment:
      dev_repo: "docker-local"
      prod_repo: "docker-prod"
      imagename: "artifactory.nohara/docker-local"
      
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Configure gcloud cli
          command: |
            echo $key>key.json
            gcloud auth activate-service-account --key-file=key.json
            gcloud beta container clusters get-credentials $cluster --region $region --project $project

      - run:
          name: test
          command: |
            kubectl apply -f nginx.yaml
            kubectl get pods -o wide
