version: 2
#jobs:
#  build:
#    docker:
#      - image: minepicco/cc-build-image:24
jobs:
  build:
    executor: machine
    environment:
      dev_repo: "docker-local"
      prod_repo: "docker-prod"
      imagename: "artifactory.nohara/docker-local"
      
    steps:
      - checkout
#      - setup_remote_docker
      
      - run:
          name: Prepare Environment -- Install JFrog CLI
          command: |
            sudo apt-get update && sudo apt-get install -y python wget curl jq
            curl -fL https://getcli.jfrog.io | sh
      - run:
          name: Prepare Environment -- Add insecure-registries
          command: |
            echo '{ "insecure-registries" : ["artifactory.nohara"] }' > daemon.json
            sudo mv daemon.json /etc/docker/
            sudo cat /etc/hosts > hosts && echo $addr" artifactory.nohara" >> hosts
            sudo mv hosts /etc/
            sudo service docker restart
      - run:
          name: Prepare Environment -- Install gcloud CLI
          command: |
            echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            sudo apt-get install -y apt-transport-https ca-certificates gnupg
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
            sudo apt-get update && sudo apt-get install -y google-cloud-sdk
      - run:
          name: Prepare Environment -- Install kubectl
          command: |
            curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
            echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
            sudo apt-get update
            sudo apt-get install -y kubectl

#            echo $addr" artifactory.nohara" >> /etc/hosts
                     
      - run:
          name: Build Image
          command: |
            echo $CIRCLE_PROJECT_REPONAME
            docker build --tag $imagename"/"$CIRCLE_PROJECT_REPONAME":"$CIRCLE_BUILD_NUM .

      - run:
          name: JFrogCLI config
          command: |
            ./jfrog rt config --user=$juser --password=$jpass --url="http://artifactory.nohara/artifactory" $jid
      - run:
          name: JFrogCLI image push and scan
          command: |
            ./jfrog rt docker-push $imagename"/"$CIRCLE_PROJECT_REPONAME":"$CIRCLE_BUILD_NUM $dev_repo --build-name=$CIRCLE_PROJECT_REPONAME --build-number=$CIRCLE_BUILD_NUM
            ./jfrog rt bce $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM
            ./jfrog rt bag $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM
            ./jfrog rt bp $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM
            ./jfrog rt bs $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM
      - run:
          name: JFrogCLI promote image to production
          command: |
            ./jfrog rt bpr $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM $prod_repo
#      - run:
#          name: Configure gcloud cli
#          command: |
#            gcloud init
#      - run:
#          name: auth and push
#          command: |
#            docker login http://artifactory.nohara -u $juser -p $jpass
#            docker push "artifactory.nohara/"$repo"/"$CIRCLE_PROJECT_REPONAME":"$CIRCLE_BUILD_NUM
            
#      - run:
#          name: JFrogCLI artifact publish
#          command: |
#            ./jfrog rt docker-push "artifactory.nohara/"$repo"/"$CIRCLE_PROJECT_REPONAME":"$CIRCLE_BUILD_NUM $repo --build-name=$CIRCLE_PROJECT_REPONAME --build-number=$CIRCLE_BUILD_NUM
#            ./jfrog rt bce $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM
#            ./jfrog rt bag $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM
#            ./jfrog rt bp $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM
#            ./jfrog rt bs $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM
#            ./jfrog rt bpr $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM $repo
           
