version: 2
jobs:
  build:
    docker:
      - image: minepicco/cc-build-image:24
#jobs:
#  build:
#    executor: machine
#    environment:
#      repo: "docker-local"
      
    steps:
      - checkout
      - setup_remote_docker
      
      - run:
          name: Prepare Environment
          command: |
            echo $addr" artifactory.nohara" >> /etc/hosts
#            sudo apt-get update && sudo apt-get install -y python wget curl jq
#            curl -fL https://getcli.jfrog.io | sh
#            echo '{ "insecure-registries" : ["artifactory.nohara"] }' > daemon.json
#            sudo mv daemon.json /etc/docker/
#            sudo cat /etc/hosts > hosts && echo $addr" artifactory.nohara" >> hosts
#            sudo mv hosts /etc/
#            sudo service docker restart
            
          
      - run:
          name: Build Image
          command: |
            echo $CIRCLE_PROJECT_REPONAME
            docker build --tag "artifactory.nohara/docker-local/"$CIRCLE_PROJECT_REPONAME":"$CIRCLE_BUILD_NUM .

      - run:
          name: JFrogCLI config
          command: |
            /jfrog rt config --user=$juser --password=$jpass --url="https://artifactory.nohara/artifactory" $jid
            /jfrog rt ping
            /jfrog rt docker-push "artifactory.nohara/docker-local/"$CIRCLE_PROJECT_REPONAME":"$CIRCLE_BUILD_NUM $repo --build-name=$CIRCLE_PROJECT_REPONAME --build-number=$CIRCLE_BUILD_NUM
            /jfrog rt bce $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM
            /jfrog rt bag $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM
            /jfrog rt bp $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM
            /jfrog rt bs $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM
            /jfrog rt bpr $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM $repo
#      - run:
#          name: auth and push
#          command: |
#            docker login http://artifactory.nohara -u $juser -p $jpass
#            docker push "artifactory.nohara/"$repo"/"$CIRCLE_PROJECT_REPONAME":"$CIRCLE_BUILD_NUM
            
#      - run:
#          name: JFrogCLI artifact publish
#          command: |
#            ./jfrog rt docker-push "artifactory.nohara/"$repo"/"$CIRCLE_PROJECT_REPONAME":"$CIRCLE_BUILD_NUM $repo --build-name=$CIRCLE_PROJECT_REPONAME --build-number=$CIRCLE_BUILD_NUM
#            ./jfrog rt bce $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM
#            ./jfrog rt bag $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM
#            ./jfrog rt bp $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM
#            ./jfrog rt bs $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM
#            ./jfrog rt bpr $CIRCLE_PROJECT_REPONAME $CIRCLE_BUILD_NUM $repo
           
